config/routes.rb
Shopaholic::Application.routes.draw do
  get "carts/show"
  get "carts/create"
  resources :categories
  resources :carts do
     get 'payment', on: :member
  end
  resources :line_items, only: [:destroy]
  get "products/:id/colors/:color_id", to: "products#show", as: 'product'
  get "home/index"

  namespace :admin do
    resources :categories
    resources :products do
      resources :colors, shallow: true
      resources :sizes, shallow: true
    end
    resources :brands
    resource :dashboard
    root :to => 'dashboard#show', only: [:show]
  end

  resources :home
    get 'products', to: "home#products", as: :products
  root :to => 'home#index'
  
end

app/controllers/admin/dashboard_controller.rb
class Admin::DashboardController < Admin::AdminsController
  def show
    @products = Product.all.limit(5)
    @categories = Category.all.limit(10)
    @recent_products = @products.order(created_at: :desc)
  end
end

app/helpers/dashboards_helper.rb
module DashboardsHelper
end

app/views/admin/dashboard/show.html.erb
<div id="dashboard-title">Hello, Admin This is Your Dashboard</div>

<div class='box'>
  <div class="box-link">
    <%= link_to 'Add More', new_admin_category_path, class: 'pure-black-link' %>
  </div>
  <h3>Recent Categories</h3>
  <div class="box-desc">
    <div class="box-recent">
      <% @categories.each do |category| %>
        <div class="tag margin-up-5"><%= link_to category.name, admin_category_path(category), class: 'pure-black-link' %></div>
          <% end %>
     </div>
    <h4>You have <%= Category.all.count %> total Categories</h4>
    <div><%= link_to 'Show all Categories of your website', admin_categories_path, class: 'pure-blue-link' %></div>
  </div>
</div>

<div class='box'>
  <div class="box-link">
    <%= link_to 'Add More', new_admin_product_path, class: 'pure-black-link' %>
  </div>
  <h3>Recent Products</h3>
  <div class="box-desc">
    <div class="box-recent">
      <% @products.each do |product| %>
        <%= link_to(image_tag(product.colors.first.thumbnail(:medium), width: '75px'), admin_product_path(product))  %>
          <% end %>
     </div>
    <h4>You have <%= @products.count %> total Products</h4>
    <div><%= link_to 'Show all Products of your website', admin_products_path, class: 'pure-blue-link' %></div>
  </div>
</div>