config/routes.rb
Shopaholic::Application.routes.draw do
  get "carts/show"
  get "carts/create"
  resources :categories
  resources :carts do
     get 'payment', on: :member
  end
  resources :line_items, only: [:destroy]
  get "products/:id/colors/:color_id", to: "products#show", as: 'product'
  get "home/index"

  namespace :admin do
    resources :categories
    resources :products do
      resources :colors, shallow: true
      resources :sizes, shallow: true
    end
    resources :brands
    resource :dashboard
    root :to => 'dashboard#show', only: [:show]
  end

  resources :home
    get 'products', to: "home#products", as: :products
  root :to => 'home#index'
  
end

app/models/brand.rb
class Brand < ActiveRecord::Base
  has_many :categories, through: :products
  include DependencyHelper
  has_many :products, dependent: :restrict_with_exception
  has_one :image, as: :imageable

  validates :name, presence: true, length: { maximum: 255 }
  
  validates :name, format: { with: REGEXP[:name_format], multiline: true, message: "- Only letters allowed" }, uniqueness: { case_sensitive: false }, unless: "name.blank?"

end

app/controllers/admin/brands_controller.rb
class Admin::BrandsController < Admin::AdminsController
  before_action :set_brand, only: [:update, :destroy, :cannot_destroy_brand, :edit, :show]
  
  rescue_from ActiveRecord::DeleteRestrictionError, with: :cannot_destroy_brand

  def index
    @brands = Brand.page(params[:page]).per(8)
  end

  def new
    @brand = Brand.new
  end

  def create
    @brand = Brand.new(brand_params)

    if @brand.save
      redirect_to admin_brands_path, notice: 'Brand was successfully created.'
    else
      render action: :new
    end
  end

  def update
    if @brand.update(brand_params)
      redirect_to admin_brands_path, notice: "Brand #{ @brand.name } was successfully updated."
    else
      render action: :edit
    end
  end

  def destroy
    if @brand.destroy
      redirect_to admin_brands_url, notice: "Brand #{ @brand.name } was successfully destroyed."
    else
      redirect_to admin_brands_url, alert: "Brand #{ @brand.name } was not successfully destroyed."
    end
  end

  private
  def set_brand
    @brand = Brand.find_by(id: params[:id])
    redirect_to root_url, alert: "Brand not found" if(@brand.nil?)
  end

  def brand_params
    params.require(:brand).permit(:name, :logo)
  end

  def cannot_destroy_brand
    redirect_to admin_brands_path, notice: "Brand #{ @brand.name } has products..It cannot be destroyed"
  end

end

app/helpers/admin/brands_helper.rb
module Admin::BrandsHelper
end

app/views/admin/brands/_form.html.erb
<%= form_for([:admin, @brand]) do |f| %>
  <%= render partial: '/errors', locals: { object: @brand } %>

<div class='main-form'>
  <div>
    <div class='form-label'>
      <%= f.label :name, class: 'inliner-tile' %>
      <p class='mandatory'>*</p>
    </div>
    <div class='form-text'>
      <%= f.text_field :name, required: true %>
    </div>
  </div>
  <div class="form-action">
    <%= f.submit %>
  </div>
  <div id='mandatory-comment'>
    <p class='mandatory'>*mandatory field</p>
  </div>
</div>
<% end %>

app/views/admin/brands/edit.html.erb
<div class='form-head'>
  <h3>Editing brand</h3>
</div>

<%= render 'form' %>

app/views/admin/brands/index.html.erb
<div class="head">
  <h3>Brands</h3>
</div>

<div id="new-tag-btn">
  <%= button_to 'New Brand', new_admin_brand_path, class: 'new-btn btn-primary btn', method: :get %>
</div>


<div class="display-container">
  <div class='container-head'>
    <h5 class='brand-title'>Name</h5>
    <h5 class='container-content'>Actions</h5>
  </div>
  <% @brands.each do |brand| %>
    <div class='container-body'>
      <div class='brand-title'><%= brand.name %></div>
      <div class='container-content'>
        <%= link_to 'Edit', edit_admin_brand_path(brand), class: 'btn btn-primary' %>
        <%= link_to 'Destroy', admin_brand_path(brand), method: :delete,
        data: { confirm: "You are going to delete #{ brand.name } brand. Sure?" }, class: 'btn btn-primary' %>
      </div>
    </div>
  <% end %>
</div>
<div class='container-pagination'>
  <%= paginate @brands %>
</div>

app/views/admin/brands/new.html.erb
<div class='form-head'>
  <h3>New Brand</h3>
</div>

<%= render 'form' %>