config/routes.rb
Shopaholic::Application.routes.draw do
  get "carts/show"
  get "carts/create"
  resources :categories
  resources :carts do
     get 'payment', on: :member
  end
  resources :line_items, only: [:destroy]
  get "products/:id/colors/:color_id", to: "products#show", as: 'product'
  get "home/index"

  namespace :admin do
    resources :categories
    resources :products do
      resources :colors, shallow: true
      resources :sizes, shallow: true
    end
    resources :brands
    resource :dashboard
    root :to => 'dashboard#show', only: [:show]
  end

  resources :home
    get 'products', to: "home#products", as: :products
  root :to => 'home#index'
  
end

app/views/layouts/admin/admins.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Shopaholic" %></title>
    <%= csrf_meta_tags %>

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
      <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.6.1/html5shiv.js" type="text/javascript"></script>
    <![endif]-->

    <%= stylesheet_link_tag "application", :media => "all" %>
     <style type="text/css">
      body 
      {
        background: #04B4AE;
      }
    </style>

    <!-- For third-generation iPad with high-resolution Retina display: -->
    <!-- Size should be 144 x 144 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-144x144-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '144x144' %>

    <!-- For iPhone with high-resolution Retina display: -->
    <!-- Size should be 114 x 114 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-114x114-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '114x114' %>

    <!-- For first- and second-generation iPad: -->
    <!-- Size should be 72 x 72 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-72x72-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '72x72' %>

    <!-- For non-Retina iPhone, iPod Touch, and Android 2.1+ devices: -->
    <!-- Size should be 57 x 57 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png' %>

    <!-- For all other devices -->
    <!-- Size should be 32 x 32 pixels -->
    <%= favicon_link_tag 'favicon.ico', :rel => 'shortcut icon' %>

    <%= javascript_include_tag "admin_application" %>
  </head>
  <body>

    <div class="navbar navbar-fluid-top">
      <div class="navbar-inner">
        <div class="container-fluid">
          <a class="btn btn-navbar" data-target=".nav-collapse" data-toggle="collapse">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </a>
          <a class="brand" href= <%= admin_root_path %> >Shopaholic</a>
          <div class="container-fluid nav-collapse">
            <ul class="nav">
              <li><%= link_to "Categories", admin_categories_path  %></li>
              <li><%= link_to "Add Product", new_admin_product_path  %></li>
              <li><%= link_to "Products", admin_products_path  %></li>
              <li><%= link_to "Brands", admin_brands_path  %></li>
            </ul>
          </div><!--/.nav-collapse -->
        </div>
      </div>
    </div>

    <div class="container-fluid">
      <div class="row-fluid">
         <div class="span10">
          <%= bootstrap_flash %>
          <div id="dashboard-container">
            <%= yield %>
          </div>
        </div>
      </div> 

      <footer>
        <p></p>
      </footer>

    </div> <!-- /container -->

  </body>
</html>