config/routes.rb
Shopaholic::Application.routes.draw do
  get "carts/show"
  get "carts/create"
  resources :categories
  resources :carts do
     get 'payment', on: :member
  end
  resources :line_items, only: [:destroy]
  get "products/:id/colors/:color_id", to: "products#show", as: 'product'
  get "home/index"

  namespace :admin do
    resources :categories
    resources :products do
      resources :colors, shallow: true
      resources :sizes, shallow: true
    end
    resources :brands
    resource :dashboard
    root :to => 'dashboard#show', only: [:show]
  end

  resources :home
    get 'products', to: "home#products", as: :products
  root :to => 'home#index'
  
end

app/models/product.rb
class Product < ActiveRecord::Base
  include DependencyHelper
  
  has_many :sizes, through: :colors
  has_many :colors
  belongs_to :category
  belongs_to :brand
  after_touch :set_published

  scope :published, -> { where published: true }
  
  validates :title, presence: true, length: { maximum: 255 }
  validates :title, format: { with: REGEXP[:name_format], multiline: true, message: "- Special characters not allowed" }, unless: "title.blank?"
  validates :title, uniqueness: { case_sensitive: false }
  validates :description, presence: true, length: { maximum: 1000 }

  private
  def set_published
    if colors.published.exists?
      update_attributes(published: true)
    else
      update_attributes(published: false)
    end
    true
  end
end

app/controllers/admin/products_controller.rb
class Admin::ProductsController < Admin::AdminsController
  before_action :set_product, only: [:show, :edit, :update, :destroy]

  def index
    @products = Product.page(params[:page]).per(8)
  end

  def new
    @product = Product.new
    @categories = Category.all
    @brands = Brand.all
  end

  def show
    @sizes = @product.sizes.order(:color_id)
  end
  
  def destroy
    if(@product.destroy)
      redirect_to admin_products_url(@product.category), notice: "Product #{ @product.title } was destroyed successfully."
    else
      redirect_to admin_products_url(@product.category), alert: "Product #{ @product.title } could not be destroyed."
    end
  end

  def create
    @product = Product.new(product_params)
    if @product.save
      redirect_to admin_products_path, notice: "Product #{ @product.title } was successfully created."
    else
      render action: :new
    end
  end

  def edit
    @brands = Brand.all
    @categories = Category.all
  end

  def update
    if @product.update(product_params)
      redirect_to admin_products_path(@product.category), notice: "Product #{ @product.title } was successfully updated."
    else
      render action: :edit
    end
  end

  private
  def set_product
    @product = Product.includes(colors: [:images, :sizes]).find_by(id: params[:id])
    redirect_to admin_products_path, alert: 'Product Not found' if(@product.nil?)
  end

  def product_params
    params.require(:product).permit(:title, :description, :category_id, :brand_id)
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
end

app/helpers/admin/products_helper.rb
module Admin::ProductsHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/admin/products/_form.html.erb
<%= form_for [:admin, @product] do |f| %>
  <%= render partial: '/errors', locals: { object: @product } %>
  <div class='main-form'>
    <div>
      <div class='form-label'>
        <%= f.label :category %>
      </div>
      <div class='form-list'>
        <%= f.collection_select :category_id, @categories, :id, :name  %>
      </div>
    </div>
    <div>
      <div class='form-label'>
        <%= f.label :brand %>
      </div>
      <div class='form-list'>
        <%= f.collection_select :brand_id, @brands, :id, :name %>
      </div>
    </div>

    <div class="field">
      <div class='form-label'>
        <%= f.label :title, class: 'inliner-tile' %>
        <p class='mandatory'>*</p>
      </div>
      <div class='form-text'>
        <%= f.text_field :title, required: true %>
      </div>
    </div>

    <div class="field">
      <div class='form-label'>
        <%= f.label :description, class: 'inliner-tile' %>
        <p class='mandatory'>*</p>
      </div>
      <div class='form-text'>
        <%= f.text_area :description, required: true %>
      </div>
    </div>
    <div class="form-action">
      <%= f.submit %>
    </div>
    <div id='mandatory-comment'>
      <p class='mandatory'>*mandatory field</p>
    </div>
  </div>
<% end %>

app/views/admin/products/edit.html.erb
<div class='form-head'>
  <h3>Editing Product</h3>
</div>

<%= render 'form' %>

app/views/admin/products/index.html.erb
<div class="head">
  <h3>Products</h3>
</div>

<div id="new-tag-btn">
  <%= button_to 'New Product', new_admin_product_path, class: 'new-btn btn-primary btn', method: :get %>
</div>

<div class="display-container">
  <div class='container-head'>
    <h5 class='container-title'>Title</h5>
    <h5 class='container-description'>Description</h5>
    <h5 class='container-content'>Actions</h5>
  </div>
  <% @products.each do |product| %>
    <div class='container-body'>
      <div class='container-title'><%= product.title %></div>
      <p class='container-description'><%= product.description %></p>
      <div class='container-content'>
        <%= link_to 'Show Product', admin_product_path(product), class: 'btn btn-primary' %>
        <%= link_to 'Edit', edit_admin_product_path(product), class: 'btn btn-primary' %>
        <%= link_to 'Destroy', admin_product_path(product), method: :delete,
        data: { confirm: "You are going to delete #{ product.title } product. Sure?" }, class: 'btn btn-primary' %>
      </div>
    </div>
  <% end %>
</div>
<div class='container-pagination'>
  <%= paginate @products %>
</div>

app/views/admin/products/new.html.erb
<div class='form-head'>
  <h3>New Product</h3>
</div>

<%= render 'form' %> 

app/views/admin/products/show.html.erb
<div id='product-content'>
  <div class="product-desc" id="product-head">
    <p>Title: <%= @product.title %></p>
    <p>Description: <%= @product.description %></p>
  </div>

  <div class="product-desc color-box">
    <%= render 'admin/colors/product_color' %>
  </div>
  <div class="product-desc size-box">
    <%= render 'admin/sizes/color_size' %>
  </div>
</div>